
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd myapp
        python3 manage.py test
        
        
  job_2:
          name:  Building image and pushing into repository
          needs: test
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
          - name: Build the Docker image of sqlmap
            run: docker build -t manage.py .
            
  job_3:
      name: uploading
      needs: job_2
      runs-on: ubuntu-latest
      steps:
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: harshametla/new1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
