
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd myapp
        python3 manage.py test
        
  job_3:
      name:  building sqlmap image and pushing into repository
      needs: test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image 
        run: docker build -f Dockerfile .
      - name: uploading
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: harshametla/new
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
